print("Hello world")
print("Happy coding")
print("Week 1 PLP Academy done - 15 to go")
print("Week 2 starting tomorrow")

print("Week 2")
print(" Learnt Advanced Git and Github")
print("Learnt Python Navigation")
print("Learnt about Pitching Software Project")
print("Had one on one talks with instuctors")
print("Quiz")

print("Week 3 - 03/10/2025")
print("Introduced to HTML")
print("Learnt Python")
print("Learnt Databases")
